### PR TITLE
feat: try deploy to aws first attempt

### PR DESCRIPTION
**Pull request by mishraomp**
- [x] Database Working
- [x] flyway working
- [x] nest api deployed
- [x] Health check passing
- [x] ALB working
- [x] API route working
- [x] UI Build And Deploy working
- [x] UI able to call out API
 @marcellmueller , done, https://d9wdul80qistx.cloudfront.net/
 cc @DerekRoberts

### CODE REVIEW

**Comment by mishraomp** [comment]
@marcellmueller got the rds deployed through TF in this PR following FAM, https://github.com/bcgov/quickstart-aws-containers/actions/runs/12215229080/job/34076925433

I am leaning towards TF now ;)

**Review by DerekRoberts — APPROVED** [review]
Very cool. :)

**Comment by mishraomp** [comment]
closing to nuke env

**Comment by marcellmueller** [comment]
> * [x]  Database Working
> * [x]  flyway working
> * [x]  nest api deployed
> * [x]  Health check passing
> * [x]  ALB working
> * [x]  API route working
> * [x]  UI Build And Deploy working
> * [x]  UI able to call out API
>   @marcellmueller , done, https://d9wdul80qistx.cloudfront.net/
>   cc @DerekRoberts

Wow that looks great, you got it up and running so quick as well! Thanks again for this :)

**Comment by DerekRoberts** [comment]
Great work, @mishraomp! We are so going to use this. :)

**Comment by mishraomp** [comment]
> Great work, @mishraomp! We are so going to use this. :)

Time to spend some time in Aws and create some good pattern for ci/cd on containers, would love your SME input

**Comment by DerekRoberts** [comment]
@mishraomp Of course!  We're in this together.  ...and might drag @marcellmueller in too.  :D + :P

**Comment by mishraomp** [comment]
closing to nuke resources

**Pull request merged**
